language: java

jdk:
  - oraclejdk8

os:
  - linux

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(echo cd de.carne.certmgr; curl -s https://codecov.io/bash)
  - bash <(echo cd de.carne; curl -s https://codecov.io/bash) -t a881b42b-df99-4330-88e8-91c25988dd52
  - bash <(echo cd de.carne.jfx; curl -s https://codecov.io/bash) -t e0e8d917-0d54-4579-ab40-aec292cce610

notifications:
  email:
    recipients:
      - hdecarne@gmail.com

# Install latest JDK, as JavaFX depends on it
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

# See https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
